
#include <vector>
#include <cassert>

#include "enums.hpp"
#include "util.hpp"

const char* ImageFormatToString(VTFImageFormat format) {
	switch(format) {
		case IMAGE_FORMAT_RGBA8888: return "IMAGE_FORMAT_RGBA8888";
		case IMAGE_FORMAT_ABGR8888: return "IMAGE_FORMAT_ABGR8888"; 
		case IMAGE_FORMAT_RGB888: return "IMAGE_FORMAT_RGB888"; 
		case IMAGE_FORMAT_BGR888: return "IMAGE_FORMAT_BGR888"; 
		case IMAGE_FORMAT_RGB565: return "IMAGE_FORMAT_RGB565"; 
		case IMAGE_FORMAT_I8: return "IMAGE_FORMAT_I8"; 
		case IMAGE_FORMAT_IA88: return "IMAGE_FORMAT_IA88"; 
		case IMAGE_FORMAT_P8: return "IMAGE_FORMAT_P8"; 
		case IMAGE_FORMAT_A8: return "IMAGE_FORMAT_A8"; 
		case IMAGE_FORMAT_RGB888_BLUESCREEN: return "IMAGE_FORMAT_RGB888_BLUESCREEN"; 
		case IMAGE_FORMAT_BGR888_BLUESCREEN: return "IMAGE_FORMAT_BGR888_BLUESCREEN"; 
		case IMAGE_FORMAT_ARGB8888: return "IMAGE_FORMAT_ARGB8888"; 
		case IMAGE_FORMAT_BGRA8888: return "IMAGE_FORMAT_BGRA8888"; 
		case IMAGE_FORMAT_DXT1: return "IMAGE_FORMAT_DXT1"; 
		case IMAGE_FORMAT_DXT3: return "IMAGE_FORMAT_DXT3"; 
		case IMAGE_FORMAT_DXT5: return "IMAGE_FORMAT_DXT5"; 
		case IMAGE_FORMAT_BGRX8888: return "IMAGE_FORMAT_BGRX8888"; 
		case IMAGE_FORMAT_BGR565: return "IMAGE_FORMAT_BGR565"; 
		case IMAGE_FORMAT_BGRX5551: return "IMAGE_FORMAT_BGRX5551"; 
		case IMAGE_FORMAT_BGRA4444: return "IMAGE_FORMAT_BGRA4444"; 
		case IMAGE_FORMAT_DXT1_ONEBITALPHA: return "IMAGE_FORMAT_DXT1_ONEBITALPHA"; 
		case IMAGE_FORMAT_BGRA5551: return "IMAGE_FORMAT_BGRA5551"; 
		case IMAGE_FORMAT_UV88: return "IMAGE_FORMAT_UV88"; 
		case IMAGE_FORMAT_UVWQ8888: return "IMAGE_FORMAT_UVWQ8888"; 
		case IMAGE_FORMAT_RGBA16161616F: return "IMAGE_FORMAT_RGBA16161616F"; 
		case IMAGE_FORMAT_RGBA16161616: return "IMAGE_FORMAT_RGBA16161616"; 
		case IMAGE_FORMAT_UVLX8888: return "IMAGE_FORMAT_UVLX8888"; 
		case IMAGE_FORMAT_R32F: return "IMAGE_FORMAT_R32F"; 
		case IMAGE_FORMAT_RGB323232F: return "IMAGE_FORMAT_RGB323232F"; 
		case IMAGE_FORMAT_RGBA32323232F: return "IMAGE_FORMAT_RGBA32323232F"; 
		case IMAGE_FORMAT_NV_DST16: return "IMAGE_FORMAT_NV_DST16"; 
		case IMAGE_FORMAT_NV_DST24: return "IMAGE_FORMAT_NV_DST24"; 					
		case IMAGE_FORMAT_NV_INTZ: return "IMAGE_FORMAT_NV_INTZ"; 
		case IMAGE_FORMAT_NV_RAWZ: return "IMAGE_FORMAT_NV_RAWZ"; 
		case IMAGE_FORMAT_ATI_DST16: return "IMAGE_FORMAT_ATI_DST16"; 
		case IMAGE_FORMAT_ATI_DST24: return "IMAGE_FORMAT_ATI_DST24"; 
		case IMAGE_FORMAT_NV_NULL: return "IMAGE_FORMAT_NV_NULL"; 
		case IMAGE_FORMAT_ATI2N: return "IMAGE_FORMAT_ATI2N"; 						
		case IMAGE_FORMAT_ATI1N: return "IMAGE_FORMAT_ATI1N"; 
		case IMAGE_FORMAT_COUNT: return "IMAGE_FORMAT_COUNT"; 
		case IMAGE_FORMAT_NONE: return "IMAGE_FORMAT_NONE";
		default: assert(0);
	}
}

VTFImageFormat ImageFormatFromString(const char* arg) {
	if(strcasecmp("IMAGE_FORMAT_RGBA8888", arg) == 0) return IMAGE_FORMAT_RGBA8888;
	else if(strcasecmp("IMAGE_FORMAT_ABGR8888", arg) == 0) return IMAGE_FORMAT_ABGR8888;
	else if(strcasecmp("IMAGE_FORMAT_RGB888", arg) == 0) return IMAGE_FORMAT_RGB888;
	else if(strcasecmp("IMAGE_FORMAT_BGR888", arg) == 0) return IMAGE_FORMAT_BGR888;
	else if(strcasecmp("IMAGE_FORMAT_RGB565", arg) == 0) return IMAGE_FORMAT_RGB565;
	else if(strcasecmp("IMAGE_FORMAT_I8", arg) == 0) return IMAGE_FORMAT_I8;
	else if(strcasecmp("IMAGE_FORMAT_IA88", arg) == 0) return IMAGE_FORMAT_IA88;
	else if(strcasecmp("IMAGE_FORMAT_P8", arg) == 0) return IMAGE_FORMAT_P8;
	else if(strcasecmp("IMAGE_FORMAT_A8", arg) == 0) return IMAGE_FORMAT_A8;
	else if(strcasecmp("IMAGE_FORMAT_RGB888_BLUESCREEN", arg) == 0) return IMAGE_FORMAT_RGB888_BLUESCREEN;
	else if(strcasecmp("IMAGE_FORMAT_BGR888_BLUESCREEN", arg) == 0) return IMAGE_FORMAT_BGR888_BLUESCREEN;
	else if(strcasecmp("IMAGE_FORMAT_ARGB8888", arg) == 0) return IMAGE_FORMAT_ARGB8888;
	else if(strcasecmp("IMAGE_FORMAT_BGRA8888", arg) == 0) return IMAGE_FORMAT_BGRA8888;
	else if(strcasecmp("IMAGE_FORMAT_DXT1", arg) == 0) return IMAGE_FORMAT_DXT1;
	else if(strcasecmp("IMAGE_FORMAT_DXT3", arg) == 0) return IMAGE_FORMAT_DXT3;
	else if(strcasecmp("IMAGE_FORMAT_DXT5", arg) == 0) return IMAGE_FORMAT_DXT5;
	else if(strcasecmp("IMAGE_FORMAT_BGRX8888", arg) == 0) return IMAGE_FORMAT_BGRX8888;
	else if(strcasecmp("IMAGE_FORMAT_BGR565", arg) == 0) return IMAGE_FORMAT_BGR565;
	else if(strcasecmp("IMAGE_FORMAT_BGRX5551", arg) == 0) return IMAGE_FORMAT_BGRX5551;
	else if(strcasecmp("IMAGE_FORMAT_BGRA4444", arg) == 0) return IMAGE_FORMAT_BGRA4444;
	else if(strcasecmp("IMAGE_FORMAT_DXT1_ONEBITALPHA", arg) == 0) return IMAGE_FORMAT_DXT1_ONEBITALPHA;
	else if(strcasecmp("IMAGE_FORMAT_BGRA5551", arg) == 0) return IMAGE_FORMAT_BGRA5551;
	else if(strcasecmp("IMAGE_FORMAT_UV88", arg) == 0) return IMAGE_FORMAT_UV88;
	else if(strcasecmp("IMAGE_FORMAT_UVWQ8888", arg) == 0) return IMAGE_FORMAT_UVWQ8888;
	else if(strcasecmp("IMAGE_FORMAT_RGBA16161616F", arg) == 0) return IMAGE_FORMAT_RGBA16161616F;
	else if(strcasecmp("IMAGE_FORMAT_RGBA16161616", arg) == 0) return IMAGE_FORMAT_RGBA16161616;
	else if(strcasecmp("IMAGE_FORMAT_UVLX8888", arg) == 0) return IMAGE_FORMAT_UVLX8888;
	else if(strcasecmp("IMAGE_FORMAT_R32F", arg) == 0) return IMAGE_FORMAT_R32F;
	else if(strcasecmp("IMAGE_FORMAT_RGB323232F", arg) == 0) return IMAGE_FORMAT_RGB323232F;
	else if(strcasecmp("IMAGE_FORMAT_RGBA32323232F", arg) == 0) return IMAGE_FORMAT_RGBA32323232F;
	else if(strcasecmp("IMAGE_FORMAT_NV_DST16", arg) == 0) return IMAGE_FORMAT_NV_DST16;
	else if(strcasecmp("IMAGE_FORMAT_NV_DST24", arg) == 0) return IMAGE_FORMAT_NV_DST24;
	else if(strcasecmp("IMAGE_FORMAT_NV_INTZ", arg) == 0) return IMAGE_FORMAT_NV_INTZ;
	else if(strcasecmp("IMAGE_FORMAT_NV_RAWZ", arg) == 0) return IMAGE_FORMAT_NV_RAWZ;
	else if(strcasecmp("IMAGE_FORMAT_ATI_DST16", arg) == 0) return IMAGE_FORMAT_ATI_DST16;
	else if(strcasecmp("IMAGE_FORMAT_ATI_DST24", arg) == 0) return IMAGE_FORMAT_ATI_DST24;
	else if(strcasecmp("IMAGE_FORMAT_NV_NULL", arg) == 0) return IMAGE_FORMAT_NV_NULL;
	else if(strcasecmp("IMAGE_FORMAT_ATI2N", arg) == 0) return IMAGE_FORMAT_ATI2N;
	else if(strcasecmp("IMAGE_FORMAT_ATI1N", arg) == 0) return IMAGE_FORMAT_ATI1N;
	else if(strcasecmp("IMAGE_FORMAT_COUNT", arg) == 0) return IMAGE_FORMAT_COUNT;
	else return IMAGE_FORMAT_NONE;
}

std::vector<std::string> TextureFlagsToStringVector(std::uint32_t flags) {
	std::vector<std::string> ret;
	if(flags &TEXTUREFLAGS_POINTSAMPLE) ret.push_back("TEXTUREFLAGS_POINTSAMPLE");
	if(flags &TEXTUREFLAGS_TRILINEAR) ret.push_back("TEXTUREFLAGS_TRILINEAR");
	if(flags &TEXTUREFLAGS_CLAMPS) ret.push_back("TEXTUREFLAGS_CLAMPS");
	if(flags &TEXTUREFLAGS_CLAMPT) ret.push_back("TEXTUREFLAGS_CLAMPT");
	if(flags &TEXTUREFLAGS_ANISOTROPIC) ret.push_back("TEXTUREFLAGS_ANISOTROPIC");
	if(flags &TEXTUREFLAGS_HINT_DXT5) ret.push_back("TEXTUREFLAGS_HINT_DXT5");
	if(flags &TEXTUREFLAGS_SRGB) ret.push_back("TEXTUREFLAGS_SRGB");
	if(flags &TEXTUREFLAGS_DEPRECATED_NOCOMPRESS) ret.push_back("TEXTUREFLAGS_DEPRECATED_NOCOMPRESS");
	if(flags &TEXTUREFLAGS_NORMAL) ret.push_back("TEXTUREFLAGS_NORMAL");
	if(flags &TEXTUREFLAGS_NOMIP) ret.push_back("TEXTUREFLAGS_NOMIP");
	if(flags &TEXTUREFLAGS_NOLOD) ret.push_back("TEXTUREFLAGS_NOLOD");
	if(flags &TEXTUREFLAGS_MINMIP) ret.push_back("TEXTUREFLAGS_MINMIP");
	if(flags &TEXTUREFLAGS_PROCEDURAL) ret.push_back("TEXTUREFLAGS_PROCEDURAL");
	if(flags &TEXTUREFLAGS_ONEBITALPHA) ret.push_back("TEXTUREFLAGS_ONEBITALPHA");
	if(flags &TEXTUREFLAGS_EIGHTBITALPHA) ret.push_back("TEXTUREFLAGS_EIGHTBITALPHA");
	if(flags &TEXTUREFLAGS_ENVMAP) ret.push_back("TEXTUREFLAGS_ENVMAP");
	if(flags &TEXTUREFLAGS_RENDERTARGET) ret.push_back("TEXTUREFLAGS_RENDERTARGET");
	if(flags &TEXTUREFLAGS_DEPTHRENDERTARGET) ret.push_back("TEXTUREFLAGS_DEPTHRENDERTARGET");
	if(flags &TEXTUREFLAGS_NODEBUGOVERRIDE) ret.push_back("TEXTUREFLAGS_NODEBUGOVERRIDE");
	if(flags &TEXTUREFLAGS_SINGLECOPY) ret.push_back("TEXTUREFLAGS_SINGLECOPY");
	if(flags &TEXTUREFLAGS_UNUSED0) ret.push_back("TEXTUREFLAGS_UNUSED0");
	if(flags &TEXTUREFLAGS_DEPRECATED_ONEOVERMIPLEVELINALPHA) ret.push_back("TEXTUREFLAGS_DEPRECATED_ONEOVERMIPLEVELINALPHA");
	if(flags &TEXTUREFLAGS_UNUSED1) ret.push_back("TEXTUREFLAGS_UNUSED1");
	if(flags &TEXTUREFLAGS_DEPRECATED_PREMULTCOLORBYONEOVERMIPLEVEL) ret.push_back("TEXTUREFLAGS_DEPRECATED_PREMULTCOLORBYONEOVERMIPLEVEL");
	if(flags &TEXTUREFLAGS_UNUSED2) ret.push_back("TEXTUREFLAGS_UNUSED2");
	if(flags &TEXTUREFLAGS_DEPRECATED_NORMALTODUDV) ret.push_back("TEXTUREFLAGS_DEPRECATED_NORMALTODUDV");
	if(flags &TEXTUREFLAGS_UNUSED3) ret.push_back("TEXTUREFLAGS_UNUSED3");
	if(flags &TEXTUREFLAGS_DEPRECATED_ALPHATESTMIPGENERATION) ret.push_back("TEXTUREFLAGS_DEPRECATED_ALPHATESTMIPGENERATION");
	if(flags &TEXTUREFLAGS_NODEPTHBUFFER) ret.push_back("TEXTUREFLAGS_NODEPTHBUFFER");
	if(flags &TEXTUREFLAGS_UNUSED4) ret.push_back("TEXTUREFLAGS_UNUSED4");
	if(flags &TEXTUREFLAGS_DEPRECATED_NICEFILTERED) ret.push_back("TEXTUREFLAGS_DEPRECATED_NICEFILTERED");
	if(flags &TEXTUREFLAGS_CLAMPU) ret.push_back("TEXTUREFLAGS_CLAMPU");
	if(flags &TEXTUREFLAGS_VERTEXTEXTURE) ret.push_back("TEXTUREFLAGS_VERTEXTEXTURE");
	if(flags &TEXTUREFLAGS_SSBUMP) ret.push_back("TEXTUREFLAGS_SSBUMP");
	if(flags &TEXTUREFLAGS_UNUSED5) ret.push_back("TEXTUREFLAGS_UNUSED5");
	if(flags &TEXTUREFLAGS_DEPRECATED_UNFILTERABLE_OK) ret.push_back("TEXTUREFLAGS_DEPRECATED_UNFILTERABLE_OK");
	if(flags &TEXTUREFLAGS_BORDER) ret.push_back("TEXTUREFLAGS_BORDER");
	if(flags &TEXTUREFLAGS_DEPRECATED_SPECVAR_RED) ret.push_back("TEXTUREFLAGS_DEPRECATED_SPECVAR_RED");
	if(flags &TEXTUREFLAGS_DEPRECATED_SPECVAR_ALPHA) ret.push_back("TEXTUREFLAGS_DEPRECATED_SPECVAR_ALPHA");
	
	return ret;
}
